variables:
  - group: GITHUB_TOKEN

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Install
    jobs:
      - job: deps
        steps:
          - checkout: self

          - task: NodeTool@0
            displayName: "Use Node.js 18.x"
            inputs:
              versionSpec: "18.x"
              checkLatest: true

          - script: |
              cd backend
              npm ci
            displayName: "Install backend dependencies"

          - script: |
              cd frontend
              npm ci
            displayName: "Install frontend dependencies"

  - stage: LintAndTest
    jobs:
      - job: tests
        steps:
          - checkout: self

          - task: NodeTool@0
            displayName: "Use Node.js 18.x"
            inputs:
              versionSpec: "18.x"
              checkLatest: true

          - script: |
              cd backend
              npm ci
            displayName: "Install backend dependencies"

          - script: |
              cd backend
              npm run lint
            displayName: "Lint backend (warnings won't fail)"
            continueOnError: true

          - script: |
              cd backend
              npm run test
            displayName: "Test backend"

          - script: |
              cd frontend
              npm ci
            displayName: "Install frontend dependencies"

  - stage: Build
    jobs:
      - job: build
        steps:
          - checkout: self

          - task: NodeTool@0
            displayName: "Use Node.js 18.x"
            inputs:
              versionSpec: "18.x"
              checkLatest: true

          - script: |
              cd backend
              npm ci
            displayName: "Install backend dependencies"

          - script: |
              cd backend
              npm run build
            displayName: "Build backend"

          - script: |
              cd frontend
              npm ci
            displayName: "Install frontend dependencies"

          - script: |
              cd frontend
              npm run build
            displayName: "Build frontend"

          - publish: backend/dist
            artifact: backend-dist

          - publish: frontend/dist
            artifact: frontend-dist

          - checkout: self
            fetchDepth: 0

          - script: |
              git config --global user.email "damianzieba999@gmail.com"
              git config --global user.name "Damian526"
              git remote add github https://Damian526:$(GITHUB_TOKEN)@github.com/Damian526/cinema-reservation-app.git
              git push github HEAD:main --force
            displayName: "Mirror to GitHub"
